development: &development
  adapter: postgresql
  database: wedding_invitor_development
  pool: 5
  timeout: 5000
  port: 15432

test:
  adapter: postgresql
  database: wedding_invitor_test
  pool: 5
  timeout: 5000
  port: 15432

staging:
  <<: *development

production:
  <<: *development
